### ISSUE TITLE
Fix: release workflow

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/pyos-sphinx-theme#18]
@Midnighter created a nice workflow that will publish to pypi on release. We now want to set things up so

1. we use pypi trusted publisher workflows
2. we separate the build and the publish into two sections of the workflow

for reference see how we are doing things for pyosmeta. once we publish to pypi we can then create a trusted workflow using that specific project on pypi. 

https://github.com/pyOpenSci/pyosMeta/blob/main/.github/workflows/publish-pypi.yml

**Comment by lwasser** [comment]
@Revathyvenugopal162 I just merged your PR. I'm so sorry about how slow I've been responding. Would you like me to create a release, or would you like to do it?

**Comment by Revathyvenugopal162** [comment]
@lwasser could you please do the release of https://pypi.org/project/pyos-sphinx-theme/ version1.0.0? then we can start migrating the packages to this theme

**Comment by lwasser** [comment]
i just tried to cut a release - it should all be done via github but it's throwing an error
it looks like it's building and not updating the tag as it should for the release version as it's still showing o.1dev which is a "dirty" build from the last release - 

https://pypi.org/project/pyos-sphinx-theme/ 

If you or anyone needs more permissions to play with things please let me know!!

**Comment by lwasser** [comment]
ok it looks like there are two GitHub action release workflows in this repo. we only need one.
to begin i'm going to delete - https://github.com/pyOpenSci/pyos-sphinx-theme/blob/main/.github/workflows/release.yml as it seems to not use sigstore or envts. (i think?). 
then i'm going to see if i can get the second workflow running. it could just be a pypi config issue.

**Comment by lwasser** [comment]
Ok i was just able to create a release and we are now at version 0.3. The build failed at sigstore, saying that the distribution files were already on sigstore, I think? But the new version is on PyPI. So things are working, we just have to manually bump the version in the `__init__.py` file before making a release for the time being. I"'m going to close this issue for now and open new ones specifically related to the sigstore issue and then another for versioning, which is nice to have but not required!
